print ("===============================================")
print ("=       Welcome to the game of Mad Libs       =")
print ("=                                             =")
print ("= First of all, I need to know some things... =")
print ("===============================================")

print (" ")
print (" ")
print ("Please provide me some words... ")
print (" ")
option1 = input("A adjective: ")
option2 = input("A noun: ")
option3 = input("A plural noun: ")
option4 = input("A person in the room (female): ")
option5 = input("A adjective: ")
option6 = input("A article of clothing: ")
option7 = input("A noun: ")
option8 = input("A city: ")
option9 = input("A plural noun: ")
option10 = input("A adjective: ")
option11 = input("A part of the body: ")
option12 = input("A letter of the alphabet: ")
option13 = input("A celebrity: ")
option14 = input("A plural noun: ")
option15 = input("A adjective: ")
option16 = input("A Place: ")
option17 = input("A part of the body: ")
option18 = input("A adjective: ")
option19 = input("Another adjective: ")
option20 = input("A verb: ")
option21 = input("A plural noun: ")
option22 = input("And finally a number: ")
print ("And finally the grand finally!!!!")
print (" ")
print (" ")
print (" ")
print ("There are many " + option1 + " ways to choose a/an " + option2 + " to")
print ("read. First, you could ask for recommendations from your friends and")
print (option3 + ". Just don't ask Aunt " + option4 + "-she only")
print ("reads " + option5 + " books with " + option6 + "-ripping goddesses")
print ("on the cover. If your friends and family are no help, try checking out the")
print (option7 + " Review in The " + option8 + " Times. If the " + option9)
print ("featured there are too " + option10 + " for your taste, try something a little")
print ("more low-" + option11 + ", like " + option12 + ": The " + option13)
print ("Magazine, or " + option14 + " Magazine. You could also choose a book the")
print (option15 + "-fashioned way. Head to your local library or " + option16)
print ("and browse the shelves until something catches your " + option17 + ".")
print ("Or, you could save yourself a whole lot of " + option18 + " trouble and log on")
print ("to www.bookish.com, the " + option19 + " new website to " + option20 + " for")
print ("books! With all the time you'll save not having to search for " + option21 + ".")
print ("you can read " + option22 + " more books!")
print (" ")